package com.vhosting.netconf.notification;

import com.vhosting.netconf.frame.Notification;

/**
 * This interface defines a Netconf notification.
 * 
 * @author Giuseppe Palmeri
 * @version 1.00, 02/11/2010
 */
public interface NotificationEvent
{

	/**
	 * Returns the time when the event was actually generated by the server.
	 * 
	 * @return The time when the event was actually generated by the server.
	 */
	public java.util.Date getEventTime();

	/**
	 * Load into a notification structure the values for it if exist.
	 * 
	 * @param notification
	 *            The notification structure.
	 * @return true if it has been possible to load values into the structure;
	 *         false otherwise.
	 */
	public boolean load(Notification notification);
}
